---
apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels:
    author: Sushant
spec:
  containers:
    - name: nginx
      image: nginx
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: slave
                operator: In
                values:
                  - Sushant