---
apiVersion: v1
kind: Pod
metadata:
  name: postgres-pod
  labels:
    name: postgres-pod
    author: Sushant
spec:
  containers:
    - name: postgres
      image: postgres
      ports:
        - containerPort: 5432
      env:
        - name: POSTGRES_PASSWORD
          value: sushant
        - name: POSTGRES_USER
          value: myuser
        - name: POSTGRES_DB
          value: mydb
...